<?php 
/************************************************
 Sphider-plus version 3.2019d authentication file.

 > > >  DO NOT EDIT THIS FILE. < < < 

Any modification must be done by Admin settings. 
*************************************************/

/******************************* Check for forbidden direct access ************************************/

    if (!defined('_SECURE')) die ("No direct access to authentication file");

/*********************** 
Admin access 
***********************/
   $admin       = '$1$dlJg01GA$4Zv4GPnugWJk3Bh.S/61R/';
   $admin_pw    = '$1$fA3ApZFG$UhSwrnOONBiFkRcGdVx42/';

/*********************** 
Database access 
***********************/
   $db_admin    = '$1$uXZ17obN$q9KL4J5u9p19gNe9A42IO/';
   $db_admin_pw = '$1$nOB8dnNJ$bErgFXN72aKS2j09Bx7Km1';

?>